### ISSUE TITLE
Document Approval Guide - Null value from context.GetInput<HttpRequestModel>()

### ISSUE THREAD

**Issue by aethieria** [elsa-workflows/elsa-guides#11]
Following the guide for the Document Approval workflow, and within DocumentApprovalWorkflow.cs, a null value is returned by context.GetInput<HttpRequestModel>() on the following line when opening an instance or from the workflow registry :

`.SetVariable("Document", context => context.GetInput<HttpRequestModel>()!.Body)`

without the Document variable being set, the other references to it also throw an error. I downloaded the project and received the same error. 

I'm currently using Visual Studio 2019 version 16.10.0, and have tried with both .NET 5 and 6

**Comment by sfmskywalker** [comment]
This is expected; when building the model for display in the workflow instance & blueprint viewer, all property setters are evaluated. Many of them will fail due to lack of context. However these errors are caught, so it should not cause any issues.

If you are seeing an issue, please feel free to reopen.

**Comment by aeri** [comment]
I detected the same issue doing the Document Approval Guide Tutorial and it seems that is not captured.
The exception occurs when i click on the workflow instance to see the workflow in the instance viewer:


**Exception has occurred: CLR/System.NullReferenceException**

```
Se produjo una excepción de tipo 'System.NullReferenceException' en ElsaGuides.ContentApproval.Web.dll pero no se controló en el código del usuario: 'Object reference not set to an instance of an object.'
   en ElsaGuides.ContentApproval.Web.DocumentApprovalWorkflow.<>c.<Build>b__0_1(ActivityExecutionContext context) en /home/aeri/TTi/Workflows/ElsaGuides.ContentApproval.Web/DocumentApprovalWorkflow.cs: línea 25
   en Elsa.Activities.Primitives.SetVariableBuilderExtensions.<>c__DisplayClass2_0`1.<SetVariable>b__1(ActivityExecutionContext x)
   en Elsa.Builders.SetupActivityExtensions.<>c__DisplayClass6_0`2.<Set>b__0(ActivityExecutionContext context)
   en Elsa.Builders.SetupActivity`1.<>c__DisplayClass6_0`1.<<Set>b__0>d.MoveNext()
```

**Comment by sfmskywalker** [comment]
Just to be clear: is that exception logged as a warning, or is the process actually killed?

**Comment by aeri** [comment]
When i run in Debug mode if i click on Workflow at the Workflow Registry page, the IDE automatically takes me to the place in the code where the exception occurred, the process stops and I have to manually continue its execution. The stop indicates that the exception was not handled in the user code.

However, if I run the application without debugging mode, this exception does not occur and it works normally.

It may not be a problem since the error does not occur in production, although it surprised me when I did the tutorial because the execution stops and it is unexpected.

I use Visual Studio Code 1.58.2 with .NET 5 over GNU/Linux.

**Comment by sfmskywalker** [comment]
Sounds like you have your debugger configured to break on exceptions even if they are handled. I have this setting enabled as well, so it happens for me too. It doesn’t cause any issues though. But I het that it might be confusing if you’re unaware of the reason.

We could simply *not* evaluate these properties, but then the designer wouldn’t be able to show the evaluated values. Even if they are literal values.

**Comment by aeri** [comment]
I see the issue, as far as I can see it is not a problem and it is something that by its nature as you say it is possible to assume. Perhaps the user could be alerted in the guide of this behavior so that it does not fall like me in a false alarm. 

The main thing seemed to me to inform the developer to corroborate that it is not a bug and that in this case we have been able to deal with. Thanks for your hard work :)

**Comment by NNPopov** [comment]
I have the same issue and I continue running app, than I see that screen. .NET 6
![image](https://user-images.githubusercontent.com/9136464/173739622-9830f0da-a70b-4932-b511-ddb9c69ddca3.png)
