### ISSUE TITLE
Document approval workflow missing HttpRequestEvent

### ISSUE THREAD

**Issue by sniperwolfpk5** [elsa-workflows/elsa-guides#3]
Hello @sfmskywalker

I am struggling to find `HttpRequestEvent`. I think you have updated it to `ReceiveHttpRequest ` but if use `ReceiveHttpRequest ` It returns empty Document variable with the following error

```
Elsa.Expressions.WorkflowExpressionEvaluator: Error: Error while evaluating JavaScript expression "Document.Author.Email". Message: Document is null

TypeError: Document is null
Elsa.Services.ActivityInvoker: Error: Error while invoking activity activity-3 of workflow 521455e00da3410da2e167d486855c33
```

I also tried Dashboard version [document approval workflow](https://elsa-workflows.github.io/elsa-core/docs/assets/document-approval-workflow.json) but it has same issue. It uses `HttpRequestEvent`

I would appreciate your help

**Comment by sniperwolfpk5** [comment]
> I also tried [Dashboard version document](https://elsa-workflows.github.io/elsa-core/docs/assets/document-approval-workflow.json) approval workflow but it has same issue. It uses HttpRequestEvent

I updated json file with newer classes but it give me same error when using dashboard. I reviewed flow it crashes on `SendEmail` activity with the same error as mentioned in original post

**Comment by sfmskywalker** [comment]
Hi @sniperwolfpk5 

You are correct: the activity you mentioned is now indeed called `ReceiveHttpRequest `.
As I tried reproducing the issue you reported I discovered the following causes:

1. There's been a breaking change that makes the JS expression `"lastResult().Content"` invalid. The correct expression is now: `"lastResult().Body"`.
2. Due to a bug in the JS evaluator, boolean (and other type) JS expressions would fail when the workflow expression is of type `WorkflowExpression<object>` - the evaluator would simply fail.

I have fixed the bug and updated the sample code. Please let me know if you run into any other issues.

Thanks for reporting!

**Comment by sniperwolfpk5** [comment]
@sfmskywalker Thank you for quick replay and fix. lastResult().Body fixes my issue.

**Comment by sniperwolfpk5** [comment]
@sfmskywalker 

Please update [document approval workflow](https://elsa-workflows.github.io/elsa-core/docs/guides-document-approval) with updated classes

**Comment by sfmskywalker** [comment]
Indeed, thanks for pointing that out. I just pushed an updated guide.

**Comment by sniperwolfpk5** [comment]
Appreciate your hard work. Thanks
