### ISSUE TITLE
Elsa - Hello Dashboard - Can't run Elsa Dashboard

### ISSUE THREAD

**Issue by DeepikaRajamanickam** [elsa-workflows/elsa-guides#4]
Trying the Hello dashboard from https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard
Run EF Migrations - while setting up the EF connection string,
Getting this error - The term "Cache=Shared" is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again

Eliminating this "Cache=Shared" couldn't create the Database instance,
![image](https://user-images.githubusercontent.com/74914250/99968755-92cf6180-2dbf-11eb-9bf6-f6bd0693cf2e.png)

**Comment by russellward** [comment]
@DeepikaRajamanickam I too have hit the same issues trying to get the dashboard up and running. Try to not use Powershell, but instead a normal Command Line, then you'll get past where you are at. Also be sure to use dotnet core 3.1, otherwise the next step... running ef migrate will fall over. This project is not compatible with .Net 5 it seems

**Comment by atorres16** [comment]
@DeepikaRajamanickam  I did this and it worked

1) Run Visual Studio as Adminitrator
2) Manually create C:/Data folder

**Comment by sfmskywalker** [comment]
The guides are being updated to Elsa 2 (in the `elsa-2.0` branch for now until Elsa 2.0 is released).
